name: Code Coverage

on: [push]

jobs:
    upload-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12 # Replace '3.x' with your desired Python version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests and generate coverage
              run: |
                  cd test
                  coverage run --source=test -m pytest test_*.py
                  coverage xml -i

            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
